// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "Paris",
                            Options = "[\"Berlin\",\"Madrid\",\"Paris\",\"Rome\"]",
                            QuestionText = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "Mars",
                            Options = "[\"Earth\",\"Mars\",\"Jupiter\",\"Venus\"]",
                            QuestionText = "Which planet is known as the Red Planet?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "Pacific Ocean",
                            Options = "[\"Atlantic Ocean\",\"Indian Ocean\",\"Arctic Ocean\",\"Pacific Ocean\"]",
                            QuestionText = "What is the largest ocean on Earth?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "William Shakespeare",
                            Options = "[\"William Shakespeare\",\"Charles Dickens\",\"Jane Austen\",\"Mark Twain\"]",
                            QuestionText = "Who wrote the play 'Romeo and Juliet'?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "H2O",
                            Options = "[\"H2O\",\"O2\",\"CO2\",\"NaCl\"]",
                            QuestionText = "What is the chemical symbol for water?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "Blue Whale",
                            Options = "[\"Elephant\",\"Blue Whale\",\"Giraffe\",\"Hippopotamus\"]",
                            QuestionText = "What is the largest mammal in the world?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "Japan",
                            Options = "[\"China\",\"Japan\",\"South Korea\",\"Thailand\"]",
                            QuestionText = "Which country is known as the Land of the Rising Sun?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswer = "2",
                            Options = "[\"0\",\"1\",\"2\",\"3\"]",
                            QuestionText = "What is the smallest prime number?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswer = "Leonardo da Vinci",
                            Options = "[\"Leonardo da Vinci\",\"Pablo Picasso\",\"Vincent van Gogh\",\"Claude Monet\"]",
                            QuestionText = "Who painted the Mona Lisa?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswer = "Dollar",
                            Options = "[\"Euro\",\"Pound\",\"Yen\",\"Dollar\"]",
                            QuestionText = "What is the currency of the United States?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
